// <auto-generated />
using System;
using CalcioAcinque.Backend.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalcioAcinque.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521101149_AddTeamDraftAndPendingPlayer")]
    partial class AddTeamDraftAndPendingPlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Importante")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId", "CreatedAt");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.AnnouncementRead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("AnnouncementId", "PlayerId")
                        .IsUnique();

                    b.ToTable("announcement_reads");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Convocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConvocazione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRisposta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<bool>("NotificaInviata")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("StatoRisposta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("convocations");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.DraftCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Affidabilita")
                        .HasColumnType("int");

                    b.Property<int>("Bravura")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Posizione")
                        .HasColumnType("longtext");

                    b.Property<string>("Soprannome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamDraftId")
                        .HasColumnType("int");

                    b.Property<bool>("Tesserato")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TeamDraftId");

                    b.ToTable("draft_candidates");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Luogo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("NumeroGiornata")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Ora")
                        .HasColumnType("time(6)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Data");

                    b.HasIndex("TeamId", "NumeroGiornata");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.MatchAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Ammonizioni")
                        .HasColumnType("int");

                    b.Property<int?>("Assist")
                        .HasColumnType("int");

                    b.Property<int?>("Autogoal")
                        .HasColumnType("int");

                    b.Property<bool>("Convocato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Espulsioni")
                        .HasColumnType("int");

                    b.Property<bool>("GettoneConsumato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Goal")
                        .HasColumnType("int");

                    b.Property<int?>("GoalSubiti")
                        .HasColumnType("int");

                    b.Property<bool>("HaGiocato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("MinutiGiocati")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("Presente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("match_attendance");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.PendingPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Affidabilita")
                        .HasColumnType("int");

                    b.Property<int>("Bravura")
                        .HasColumnType("int");

                    b.Property<bool>("Claimed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ClaimedByPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Posizione")
                        .HasColumnType("longtext");

                    b.Property<string>("Soprannome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("Tesserato")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("pending_players");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GettoniConsumati")
                        .HasColumnType("int");

                    b.Property<int>("GettoniTotali")
                        .HasColumnType("int");

                    b.Property<bool>("IscrizionePagata")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soprannome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("TesseramentoPagato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("players");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.PlayerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("player_availabilities");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.PlayerPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Pagato")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_payments");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GettoniPerGiocatore")
                        .HasColumnType("int");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PartitePerStagione")
                        .HasColumnType("int");

                    b.Property<bool>("UseGettoni")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.TeamDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GettoniPerGiocatore")
                        .HasColumnType("int");

                    b.Property<string>("NomeTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PartitePerStagione")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UseGettoni")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("team_drafts");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.TokenTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Motivazione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId", "Timestamp");

                    b.ToTable("token_transactions");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Announcement", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.AnnouncementRead", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Announcement", "Announcement")
                        .WithMany("Reads")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Convocation", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Match", "Match")
                        .WithMany("Convocations")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Player")
                        .WithMany("Convocations")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.DraftCandidate", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.TeamDraft", "TeamDraft")
                        .WithMany("Candidates")
                        .HasForeignKey("TeamDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamDraft");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Match", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Team", "Team")
                        .WithMany("Matches")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.MatchAttendance", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Match", "Match")
                        .WithMany("Attendances")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Player")
                        .WithMany("Attendances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.PendingPlayer", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Team", "Team")
                        .WithMany("PendingPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Player", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.PlayerAvailability", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Match", "Match")
                        .WithMany("Availabilities")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Player")
                        .WithMany("Availabilities")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.PlayerPayment", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Player")
                        .WithMany("Payments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.TeamDraft", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.User", "User")
                        .WithMany("TeamDrafts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.TokenTransaction", b =>
                {
                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Match", "Match")
                        .WithMany("TokenTransactions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CalcioAcinque.Backend.Models.Entities.Player", "Player")
                        .WithMany("TokenTransactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Announcement", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Match", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Availabilities");

                    b.Navigation("Convocations");

                    b.Navigation("TokenTransactions");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Player", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Availabilities");

                    b.Navigation("Convocations");

                    b.Navigation("Payments");

                    b.Navigation("TokenTransactions");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.Team", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("PendingPlayers");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.TeamDraft", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("CalcioAcinque.Backend.Models.Entities.User", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TeamDrafts");
                });
#pragma warning restore 612, 618
        }
    }
}
